# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import showtime_pb2 as showtime__pb2


class ShowtimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMovieByTime = channel.unary_stream(
                '/Showtime/GetMovieByTime',
                request_serializer=showtime__pb2.Timestamp.SerializeToString,
                response_deserializer=showtime__pb2.MovieID.FromString,
                )
        self.Showtimes = channel.unary_stream(
                '/Showtime/Showtimes',
                request_serializer=showtime__pb2.EmptyMessage.SerializeToString,
                response_deserializer=showtime__pb2.Schedules.FromString,
                )


class ShowtimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMovieByTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Showtimes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShowtimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMovieByTime': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMovieByTime,
                    request_deserializer=showtime__pb2.Timestamp.FromString,
                    response_serializer=showtime__pb2.MovieID.SerializeToString,
            ),
            'Showtimes': grpc.unary_stream_rpc_method_handler(
                    servicer.Showtimes,
                    request_deserializer=showtime__pb2.EmptyMessage.FromString,
                    response_serializer=showtime__pb2.Schedules.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Showtime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Showtime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMovieByTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Showtime/GetMovieByTime',
            showtime__pb2.Timestamp.SerializeToString,
            showtime__pb2.MovieID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Showtimes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Showtime/Showtimes',
            showtime__pb2.EmptyMessage.SerializeToString,
            showtime__pb2.Schedules.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
