# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\t\">\n\x0b\x42ookingData\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\r\n\x05\x64\x61tes\x18\x02 \x01(\t\x12\x10\n\x08moviesId\x18\x03 \x03(\t\"\x07\n\x05\x45mpty2\x96\x01\n\x07\x42ooking\x12+\n\x0fGetListBookings\x12\x06.Empty\x1a\x0c.BookingData\"\x00\x30\x01\x12\x30\n\x13GetBookingsByUserId\x12\x07.UserId\x1a\x0c.BookingData\"\x00\x30\x01\x12,\n\nAddBooking\x12\x0c.BookingData\x1a\x0c.BookingData\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USERID']._serialized_start=17
  _globals['_USERID']._serialized_end=37
  _globals['_BOOKINGDATA']._serialized_start=39
  _globals['_BOOKINGDATA']._serialized_end=101
  _globals['_EMPTY']._serialized_start=103
  _globals['_EMPTY']._serialized_end=110
  _globals['_BOOKING']._serialized_start=113
  _globals['_BOOKING']._serialized_end=263
# @@protoc_insertion_point(module_scope)
